version: '3'

services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: ./webapp
    volumes:
      # This /usr/src/app is different than Api's.
      - ./webapp:/usr/src/app
      - webapp_todo_modules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    environment:
      PGUSER: superguy
      PGPASSWORD: superpassword
      PGDATABASE: superappdb
      PGHOST: database
      # We can have multiple database providers.
      # We explicitly indicate we want to use Postgres.
      DJANGO_DATABASE: postgresdb
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres:11
    environment:
      POSTGRES_USER: superguy
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: superappdb
    # We map from 2345 to 5432 just in case
    # Postgres is already installed in the host machine.
    ports:
      - "2345:5432"

volumes:
  webapp_todo_modules:
