version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGHOST: 'db'
      PGPASSWORD: ''
    command: python ./api/manage.py runserver --database=postgresdb
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
