version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: ./api
  ports:
    - "8000:8000"
  depends_on:
    - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
