version: 2.1

references:
  job_defaults: &job_defaults
    working_directory: ~/TodoApp
  api_working_directory: &api_working_directory
    ~/TodoApp/api
  api_cache_key: &api_cache_key
    deps5-{{ .Branch }}-{{ checksum "api/requirements.txt" }}

executors:
  python3-executor:
    docker:
      - image: circleci/python:3.6.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          PGHOST: 127.0.0.1
          PGUSER: root
          PGDATABASE: circle-test_test
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

jobs:
  build-api:
    <<: *job_defaults
    executor: python3-executor
    steps:
      - checkout
      - run: 
          name: "Change ownership for proper caching restoring."
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: *api_cache_key
      - run:
          name: "Setting up virtual environment."
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
          working_directory: *api_working_directory
      - save_cache:
          key: *api_cache_key
          paths:
            - "./api/.venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - persist_to_workspace:
          root: *api_working_directory
          paths: .
  run-api-tests:
    <<: *job_defaults
    executor: python3-executor
    steps:
      - attach_workspace:
          at: *api_working_directory
      - run:
          name: "Run api's unit tests."
          command: |
            pipenv run python manage.py test
          working_directory: *api_working_directory

workflows:
  version: 2.1
  api_build_and_test:
    jobs:
      - build-api 
      - run-api-tests:
          requires:
            - build-api
